project:
  type: website
  output-dir: docs

website:
  title: "Dashboard Demo"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - more_info.qmd
      - take_action.qmd
    page-footer: 
    background: light
    left: 
      - "Copyright 2023, Nissim Lebovits"
      

format:
  html:
    theme: 
        - mystyles.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full

editor: visual

