project:
  type: website

website:
  title: "Dashboard Demo"
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - take_action.qmd
      - more_info.qmd
    page-footer: 
    background: light
    left: 
      - "Copyright 2023, Nissim Lebovits"
      

format:
  html:
    theme: 
        - mystyles.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    layout:
      margin-left

editor: visual

